package cn.cslg.microblog.DAO;

import java.util.ArrayList;
import java.util.List;

import cn.cslg.microblog.PO.Remark;

public interface RemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated
     */
    int insert(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated
     */
    int insertSelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated
     */
    Remark selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Remark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table remark
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Remark record);

	ArrayList<Remark> selectByMicroblogid(Integer microblogid);

	List<Remark> selectFourByMicroblogid(Integer microblogid);

	List<Remark> selectPageByMicroblogId(Integer microblogid, int i, int everyPage);

	int countByMicroblogId(Integer microblogid);

}