package cn.cslg.microblog.PO;
/**
 * userid1关注userid2
 * @author gyj
 *
 */
public class Follow {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.userId1
     * 关注者
     * @mbggenerated
     */
    private Integer userid1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column follow.userId2
     * 被关注者
     * @mbggenerated
     */
    private Integer userid2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.id
     *
     * @return the value of follow.id
     * 
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.id
     *
     * @param id the value for follow.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.userId1
     *
     * @return the value of follow.userId1
     *
     * @mbggenerated
     */
    public Integer getUserid1() {
        return userid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.userId1
     *
     * @param userid1 the value for follow.userId1
     *
     * @mbggenerated
     */
    public void setUserid1(Integer userid1) {
        this.userid1 = userid1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column follow.userId2
     *
     * @return the value of follow.userId2
     *
     * @mbggenerated
     */
    public Integer getUserid2() {
        return userid2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column follow.userId2
     *
     * @param userid2 the value for follow.userId2
     *
     * @mbggenerated
     */
    public void setUserid2(Integer userid2) {
        this.userid2 = userid2;
    }
}